apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-k8s
spec:
  selector:
    matchLabels:
      app: cat-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: cat-k8s
    spec:
      containers:
        - name: cat-k8s
          image: angisemo/cat-k8s
          ports: 
            - containerPort: 3000