version: '1.0'

services:
  #mongodb services
  mongo_db:
    container_name: db_container
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  #node API service
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017/cat
    depends_on:
      - mongo_db


volumes:
  mongo_db: {}